### ISSUE TITLE
Create schedule

### ISSUE THREAD

**Issue by ryjones** [pq-code-package/pq-code-package-hackathon#1]
Mar 12 session (~1330 UTC - 2100 UTC as per original email)

**Comment by dstebila** [comment]
I had put those times based on what I knew at the time about people planning to attend.  But since then, @mkannwischer emailed me that he plans to be showing up earlier, he's in Taiwan.

**Comment by ryjones** [comment]
@dstebila pull requests accepted :)

**Comment by dstebila** [comment]
> @dstebila pull requests accepted :)

As I said, I am fully occupied with other obligations right now and need to delegate organization of this to you and the others.
