### ISSUE TITLE
document any legal requirements - such as cla (ccla/icla), licensing etc

### ISSUE THREAD

**Issue by planetf1** [pq-code-package/pq-code-package-hackathon#14]

**Comment by planetf1** [comment]
@ryjones In previous discussions the kyber package team discussed their preference for
- Apache 2.0
- MIT licensing for projects
(aside: cc-by-4.0 works well for docs)

Both are fairly unencumbered and suitable for many purposes including commercial. copyleft licenses/gpl are problematic for inclusion in commercial projects. 

I'm not yet sure what licenses may apply to code or dependencies any contributors bring along, but it would be good to know up front what we can/cannot put in the repos.

Is there any advice/restrictions from the Linux Foundation generally? (similar for copyright)
Or is this mostly down to the project to decide?

**Comment by ryjones** [comment]
@planetf1 Apache 2.0 and cc-by-4.0 is the standard. Anything else would need legal review. I would need to check on what the list of acceptable licenses are, but MIT and a few others are on the list, usually. Stick with Apache 2 and cc-by-4; also, please put in SPDX headers where possible - it makes license checking faster

**Comment by planetf1** [comment]
Yes, agreed on SPDX headers (used them in previous projects). I'll add these notes to our pages.

Related, do we need anything setup in terms of CLA/ICLAs (though these will require time to be handled)

**Comment by ryjones** [comment]
@planetf1 I will need to huddle with @hartm to get certainty.

**Comment by ryjones** [comment]
@planetf1 no CLAs, just DCO. `git commit -s ... `

**Comment by planetf1** [comment]
Ok, will add notes on DCO (and we'll enable that in branch protection rules when setting up a repository)

**Comment by planetf1** [comment]
@ryjones Could you add any necessary clarifications/details into the file 202404/licensing.md ?

**Comment by ryjones** [comment]
sit tight

**Comment by planetf1** [comment]
Closing all that were prep for this session as hackathon under way. - any issues should now be against tsc or original repos
