### ISSUE TITLE
Create main documentation site for pq-code-package

### ISSUE THREAD

**Issue by planetf1** [pq-code-package/pq-code-package-hackathon#8]

**Comment by planetf1** [comment]
We should take the opportunity provided to the hackathon to kick-start the pq-code-package documentation.

At a minimum we should be starting to :
 - document the aims/goals of the pq-code-package
 - catalog each implementation in terms of it's core characteristics
- add links to further information
 - get our processes documented (such that they are in the early days) 

I suspect detailed implementation specific docs will remain closely aligned to that project's code

As such I think we need to create a docs repository in prep for the hackathon - we may have new users, software engineers or others that aren't onboarding implementation code, but can contribute in other ways

How about pq-code-package/docs ? @ryjones ?

Just getting basic content/text written during the day is a start. Developing a richer (mkdocs?) site may happen depending on those in attendance.

**Comment by ryjones** [comment]
https://github.com/pq-code-package/documentation

**Comment by planetf1** [comment]
@ryjones Thanks for creating the clean repo (minus fork).

However the pages are not rendering using mkdocs. I presume the repo setting for pages source needs updating to point to a different branch, but I can’t check as I’m not admin. Could you take a look?

It was working previously off the fork (where I used added a commit to update some of the project related strings, and I see that commit is in the new copy(

**Comment by ryjones** [comment]
@planetf1 you now have admin

**Comment by planetf1** [comment]
Thanks for setting up. Also the redirect is fine now after your changes, plus I added an index.html

I'm now going to enable branch protection in prep for tomorrow, but for onboarding purposes am not going to assign code ownership approval, just any single approval
